server:
  port: 8081
  ssl:
    enabled: false
  tomcat:
    max-http-form-post-size: 100MB

jwt:
  secret: DjktOBVHAu0VxgLpj5HQFprityt4WamJQBeh21lA+N8=
  expiration: 86400000  # 1일 (초 단위)

jasypt:
  encryptor:
    password: dfybybily!@#$%  # 암호화에 사용한 비밀번호

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB  # 개별 파일 최대 크기 (요구사항에 따라 조정 가능)
      max-request-size: 100MB  # 요청 전체 크기 (여러 파일 포함)
      file-size-threshold: 2MB  # 임계값, 2MB 초과 시 디스크에 임시 저장

  jackson:
    serialization:
      write-date-keys-as-timestamps: false
    config:
      import: optional:file:.env[.properties]
    profiles:
      active: dev

  autoconfigure:
    application:
      name: one-dfy-bily-api
    h2:
      console:
        enabled: true
        web:
          resources:
            static-locations: classpath:/static/
    mybatis:
      mapper-locations: classpath:mapper/*.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000
  datasource:
    url: jdbc:mysql://15.164.18.21:3306/bilydatabase
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true                       # 콘솔에 SQL 출력
    properties:
      hibernate:
        format_sql: true                 # 가독성 좋은 줄바꿈
        highlight_sql: true              # ANSI 컬러 하이라이트
        # --------------------------------------------
        #  ↓ 바인딩 파라미터 로그를 위해 TRACE 레벨 필요
        # --------------------------------------------
        type:
          descriptor: TRACE

    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

  mybatis:
    configuration:
      map-underscore-to-camel-case: true

  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){green} [%thread] %clr(%-5level){cyan} %clr([%logger{36}]){blue} - %msg%n"
    level:
      root: INFO

      # --- Hibernate 실행 SQL ---
      "org.hibernate.SQL": DEBUG

      # --- Hibernate 6.x 바인딩 값 ---
      "org.hibernate.orm.jdbc.bind": TRACE

      # --- Hibernate 5.x 바인딩 값 ---
      "org.hibernate.type.descriptor.sql": TRACE



cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false

springdoc:
  api-docs:
    path: /api-docs # API 문서 경로 설정
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 경로 설정
    enabled: true # Swagger UI 활성화 여부

s3:
  path:
    inquiry: images/inquiry/
    space: images/space/space/
    use_case: images/space/useCase/
    blueprint: images/space/blueprint/
    business_card: images/business_card/

cors:
  allowed-origins: "http://localhost:3001,https://api.bily.at,http://localhost:8081"

dev:
  fallback-user-id: 110


